import { Clock } from "../models/Clock"

const clocksData: Clock[] = [
	{
	  id: 1,
	  offsetTime: "UTC -12:00",
	  timeZone: "Etc/GMT+12",
	  city: "Baker Island, USA",
	  isDigital: true,
	},
	{
	  id: 2,
	  offsetTime: "UTC -11:00",
	  timeZone: "Pacific/Pago_Pago",
	  city: "Pago Pago, American Samoa",
	  isDigital: true,
	},
	{
	  id: 3,
	  offsetTime: "UTC -10:00",
	  timeZone: "Pacific/Honolulu",
	  city: "Honolulu, USA",
	  isDigital: true,
	},
	{
	  id: 4,
	  offsetTime: "UTC -9:00",
	  timeZone: "America/Anchorage",
	  city: "Anchorage, USA",
	  isDigital: true,
	},
	{
	  id: 5,
	  offsetTime: "UTC -8:00",
	  timeZone: "America/Los_Angeles",
	  city: "Los Angeles, USA",
	  isDigital: true,
	},
	{
	  id: 6,
	  offsetTime: "UTC -7:00",
	  timeZone: "America/Denver",
	  city: "Denver, USA",
	  isDigital: true,
	},
	{
	  id: 7,
	  offsetTime: "UTC -6:00",
	  timeZone: "America/Mexico_City",
	  city: "Mexico City, Mexico",
	  isDigital: true,
	},
	{
	  id: 8,
	  offsetTime: "UTC -5:00",
	  timeZone: "America/New_York",
	  city: "New York, USA",
	  isDigital: true,
	},
	{
	  id: 9,
	  offsetTime: "UTC -4:00",
	  timeZone: "America/Caracas",
	  city: "Caracas, Venezuela",
	  isDigital: true,
	},
	{
	  id: 10,
	  offsetTime: "UTC -3:00",
	  timeZone: "America/Argentina/Buenos_Aires",
	  city: "Buenos Aires, Argentina",
	  isDigital: true,
	},
	{
	  id: 11,
	  offsetTime: "UTC -2:00",
	  timeZone: "Atlantic/South_Georgia",
	  city: "South Georgia Island, UK",
	  isDigital: true,
	},
	{
	  id: 12,
	  offsetTime: "UTC -1:00",
	  timeZone: "Atlantic/Azores",
	  city: "Azores, Portugal",
	  isDigital: true,
	},
	{
	  id: 13,
	  offsetTime: "UTC 0:00",
	  timeZone: "Europe/London",
	  city: "London, UK",
	  isDigital: true,
	},
	{
	  id: 14,
	  offsetTime: "UTC +1:00",
	  timeZone: "Europe/Paris",
	  city: "Paris, France",
	  isDigital: true,
	},
	{
	  id: 15,
	  offsetTime: "UTC +2:00",
	  timeZone: "Africa/Cairo",
	  city: "Cairo, Egypt",
	  isDigital: true,
	},
	{
	  id: 16,
	  offsetTime: "UTC +3:00",
	  timeZone: "Europe/Moscow",
	  city: "Moscow, Russia",
	  isDigital: true,
	},
	{
	  id: 17,
	  offsetTime: "UTC +4:00",
	  timeZone: "Asia/Dubai",
	  city: "Dubai, UAE",
	  isDigital: true,
	},
	{
	  id: 18,
	  offsetTime: "UTC +5:00",
	  timeZone: "Asia/Karachi",
	  city: "Karachi, Pakistan",
	  isDigital: true,
	},
	{
	  id: 19,
	  offsetTime: "UTC +6:00",
	  timeZone: "Asia/Dhaka",
	  city: "Dhaka, Bangladesh",
	  isDigital: true,
	},
	{
	  id: 20,
	  offsetTime: "UTC +7:00",
	  timeZone: "Asia/Bangkok",
	  city: "Bangkok, Thailand",
	  isDigital: true,
	},
	{
	  id: 21,
	  offsetTime: "UTC +8:00",
	  timeZone: "Asia/Shanghai",
	  city: "Shanghai, China",
	  isDigital: true,
	},
	{
	  id: 22,
	  offsetTime: "UTC +9:00",
	  timeZone: "Asia/Tokyo",
	  city: "Tokyo, Japan",
	  isDigital: true,
	},
	{
	  id: 23,
	  offsetTime: "UTC +10:00",
	  timeZone: "Australia/Brisbane",
	  city: "Brisbane, Australia",
	  isDigital: true,
	},
	{
	  id: 24,
	  offsetTime: "UTC +11:00",
	  timeZone: "Pacific/Guadalcanal",
	  city: "Honiara, Solomon Islands",
	  isDigital: true,
	},
	{
		id: 25,
		offsetTime: "UTC +12:00",
		timeZone: "Pacific/Fiji",
		city: "Suva, Fiji",
		isDigital: true,
	  }
  ]

export default clocksData
